### ISSUE TITLE
插件安装后，在IDEA的文件模板中会出现两个weex_script

### ISSUE THREAD

**Issue by cooliean** [misakuo/weex-language-support#1]
这样导致没有办法在添加自己的模板了。因为这里已经有两个重复名字的，导致没有办法保存。

**Comment by cooliean** [comment]
还有一个建议就是能否吧模板的内容公开到设置里面。

**Comment by misakuo** [comment]
欢迎就此issue提交PR: )

**Comment by misakuo** [comment]
我看了下代码，导致问题的根本原因是`<internalFileTemplate name="weex_script"/>`这里重复注册了模板，去掉即可，另外对于未知类型的文件模板会自动在New菜单里创建Item，就不用自己写Action了，可以把Action移除。模板的内容可以在`Perferences -> Editor -> File and Code Templates`里进行编辑
