### ISSUE TITLE
插件无法加载

### ISSUE THREAD

**Issue by chenzefeng09** [misakuo/weex-language-support#10]
你好，在使用中遇到两个问题：
1、在idea的插件市场中下载的1.0版本可以正常加载，但是weex的代码补全、高亮这些特性没有工作，实时编译和预览是可以的。
2、下载git版的插件安装后，加载失败，提示
Required plugin JavaScript is not enabled
请问是什么原因导致的？

**Comment by misakuo** [comment]
请问你使用的IDE是什么？该插件目前仅支持 IntelliJ IDEA、  PhpStorm、  WebStorm、  PyCharm、  RubyMine、  Gogland这几款IDE

**Comment by chenzefeng09** [comment]
IntelliJ IDEA，在android studio上也是这样，在WebStorm上可以看到js部分的高亮

**Comment by misakuo** [comment]
可能是你同时装了其他Weex插件，或者是你把we文件给关联到html上去了
