### ISSUE TITLE
关于require('weex-components')引用报错的问题

### ISSUE THREAD

**Issue by myyeshang** [misakuo/weex-language-support#12]
你好，在phpstorm里，最新版的2.0.6插件，我在编写weex文件时候，引用`require('weex-components');`发现weex log提示不存在，`ERROR: Cannot find required module "weex-components"`
里面所封装的例如<wxc-button>书写时候也无法补全，预览界面时候相应的样式也看不到。我在weex language support 里面把路径手动添加进global weex components里面去也不行，请教一下有没有遇到过这个问题的，怎么解决。

**Comment by misakuo** [comment]
请先确认是否使用npm安装了`weex-components`这个库

**Comment by myyeshang** [comment]
是确保安装了的，直接从github拉的，package.json里面`"devDependencies"`是包含这个引用的，`"weex-components": "^0.2.0",`，我也又单独执行了一次`npm install weex-components`，确保在node_modules里面是有这个文件夹的，但仍是提示错误信息，如下图：
![image](https://user-images.githubusercontent.com/23429274/29824997-9fdb191c-8c98-11e7-9a71-7c90083f6cd0.png)

**Comment by myyeshang** [comment]
但是编译后的生成js文件样式是正确无误的

**Comment by misakuo** [comment]
你或许可以把issue提到weex-components的仓库里去
