### ISSUE TITLE
PSI类文件不存在

### ISSUE THREAD

**Issue by iniself** [misakuo/weex-language-support#14]
intellij IDEA-Community-2017-3，build时提示
`Error:(7, 1) java: 程序包com.intellij.lang.javascript.psi不存在`。是不是我的SDK有问题?谢谢

**Comment by misakuo** [comment]
javascript相关的library包含在旗舰版IDEA或WebStorm中

**Comment by iniself** [comment]
我换成intellij IDEA-Ultimate，build到`import com.intellij.lang.javascript.psi.JSBlockStatement`这些内容时还是提示如下。我发现在SDK里，com.intellij.lang下面并没有javascript这些类文件。请赐教，非常感谢
`Error:(4, 40) java: 程序包com.intellij.lang.javascript.psi不存在`

**Comment by misakuo** [comment]
![img](https://img.alicdn.com/tfs/TB1hBpBbXOWBuNjy0FiXXXFxVXa-1384-448.png)

**Comment by iniself** [comment]
正确了，非常你的耐心回复。
