### ISSUE TITLE
新建weex文件格式问题

### ISSUE THREAD

**Issue by BadWooden** [misakuo/weex-language-support#3]
<template></template>

<script></script>

<style></style>
是否换成
<template></template>
<style></style>
<script></script>
合理一些

**Comment by BadWooden** [comment]
<template></template>

<script></script>

<style></style>

**Comment by BadWooden** [comment]
<template></template>
<style></style>
<script></script>

**Comment by BadWooden** [comment]
`<template></template>

<script></script>

<script></script>`

**Comment by BadWooden** [comment]
你们代码弄不是 我的意思是 脚本是否在最后

**Comment by misakuo** [comment]
可以编辑模板    
![QQ20161019-0@2x.png](https://ooo.0o0.ooo/2016/10/19/58070038ebfb1.png)
